version: "3"

services:
  my-app:
    image: cr.yandex/${REGISTRY_ID}/messenger:latest
    build:
      context: .
    environment:
      env_file:
        .env
    ports:
      - "${PORT:-3000}:3000"
    restart: always
    networks:
      - awesome
  
  # nginx:
  #   image: nginx
  #   restart: always
  #   container_name: nginx
  #   volumes:
  #     - ./data/nginx/core/default.conf:/etc/nginx/conf.d/default.conf
  #     - ./data/nginx/logs/:/var/log/nginx/

  #   depends_on:
  #     - my-app
  #   ports:
  #     - "80:80" #3000
  #     - "443:443"
  #   networks:
  #     - awesome

networks:
  awesome:
    driver: bridge
