version: "3.7"

services:
  my-app:
    image: {{ env.IMAGE_NAME }}
    platform: linux/amd64
    build:
      context: .
    environment:
      NODE_ENV: {{ env.NODE_ENV }}
      PORT: {{ env.PORT }}
    ports:
      - "{{ env.PORT }}:3000"
    restart: always
    networks:
      - awesome
      
volumes:
  pgadmin-data:

networks:
  awesome:
    driver: bridge
