export const inboxes = [
  {
    labelText: 'Старый пароль',
    name: 'oldPassword',
    placeholder: '********',
    inputType: 'password',
    labelClass: 'list__label',
    boxClass: 'list__item list__item_revers password-old',
    inputValidation: 'password',
    inputAutocomplete: 'off',
    nputId: 'password-old-input',
    inputStyle: 'list__value list__value_input password',
  },
  {
    labelText: 'Новый пароль',
    name: 'newPassword',
    placeholder: '********',
    inputType: 'password',
    labelClass: 'list__label',
    boxClass: 'list__item list__item_revers password-new',
    inputValidation: 'password',
    inputAutocomplete: 'off',
    inputId: 'password-new-input',
    inputStyle: 'list__value list__value_input password',
  },
  {
    labelText: 'Повторите новый пароль',
    name: 'newPasswordConfirm',
    placeholder: '********',
    inputType: 'password',
    labelClass: 'list__label',
    boxClass: 'list__item list__item_revers confirm-password',
    inputValidation: 'password',
    inputAutocomplete: 'off',
    inputId: 'confirm-password-input',
    inputStyle: 'list__value list__value_input password',
  }
];
