export const inboxes = [
  {
    boxClass: 'list__item list__item_revers',
    labelText: 'Почта',
    name: 'email',
    inputType: 'email',
    inputAutocomplete: 'off',
    labelClass: 'list__label',
    inputStyle: 'list__value list__value_input email',
    placeholder: '',
    inputId: 'email-input',
    inputValidation: 'email',
  },
  {
    boxClass: 'list__item list__item_revers',
    labelText: 'Логин',
    name: 'login',
    inputType: 'text',
    inputAutocomplete: 'off',
    labelClass: 'list__label',
    inputStyle: 'list__value list__value_input login',
    placeholder: '',
    inputValidation: 'login',
    inputId: 'login-input',
  },
  {
    boxClass: 'list__item list__item_revers',
    labelText: 'Имя',
    name: 'first_name',
    inputType: 'text',
    inputAutocomplete: 'off',
    labelClass: 'list__label',
    inputStyle: 'list__value list__value_input first-name',
    placeholder: '',
    inputValidation: 'first_name',
    inputId: 'first_name-input',
  },
  {
    boxClass: 'list__item list__item_revers',
    labelText: 'Фамилия',
    name: 'second_name',
    inputType: 'text',
    inputAutocomplete: 'off',
    labelClass: 'list__label',
    inputStyle: 'list__value list__value_input second-name',
    placeholder: '',
    inputValidation: 'second_name',
    inputId: 'second_name-input',
  },
  {
    boxClass: 'list__item list__item_revers',
    labelText: 'Имя в чате',
    name: 'display_name',
    inputAutocomplete: 'off',
    inputType: 'text',
    labelClass: 'list__label',
    inputStyle: 'list__value list__value_input nickname',
    placeholder: '',
    inputValidation: 'nickname',
    inputId: 'nickname-input',
  },
  {
    boxClass: 'list__item list__item_revers',
    name: 'phone',
    inputStyle: 'list__value list__value_input phone',
    inputType: 'tel',
    inputAutocomplete: 'off',
    labelText: 'Телефон',
    labelClass: 'list__label',    
    placeholder: '',
    inputValidation: 'phone',
    inputId: 'phone-input',
  }
];
