# Steps represent a sequence of tasks
# that will be executed as part of the job
steps:
    # Checks-out your repository under $GITHUB_WORKSPACE,
    # so your job can access it
    - uses: actions/checkout@v2
# Runs a single command using the runners shell
    - name: Yandex Cloud CR "Login" Action for GitHub Actions
    uses: yc-actions/yc-cr-login@v1
    with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
- name: Build, tag, and push image to Yandex Cloud Container Registry
    env:
        CR_REGISTRY: ${{ secrets.CR_REGISTRY }}
        CR_REPO: yc-cr-github-action
        IMAGE_TAG: ${{ github.sha }}
    run: |
    docker build -t cr.yandex/$CR_REGISTRY/$CR_REPO:$IMAGE_TAG .
    docker push cr.yandex/$CR_REGISTRY/$CR_REPO:$IMAGE_TAG
